import MatrixMultiplicationLowerBound25

#check MatrixMultiplicationLowerBound.theorem_one
#check MatrixMultiplicationLowerBound.theorem_one_rational
#check MatrixMultiplicationLowerBound.theorem_one_rounded
#check MatrixMultiplicationLowerBound.matrix_algorithm_rank_strict
#check MatrixMultiplicationLowerBound.rank_325_ge25
#check MatrixMultiplicationLowerBound.matrix_algorithm_rank_ge25

#print axioms MatrixMultiplicationLowerBound.theorem_one
#print axioms MatrixMultiplicationLowerBound.theorem_one_rational
#print axioms MatrixMultiplicationLowerBound.theorem_one_rounded
#print axioms MatrixMultiplicationLowerBound.matrix_algorithm_rank_strict
#print axioms MatrixMultiplicationLowerBound.rank_325_ge25
#print axioms MatrixMultiplicationLowerBound.matrix_algorithm_rank_ge25

#check MatrixMultiplicationLowerBound.Decomposition.toMatrixAlgorithm
#check MatrixMultiplicationLowerBound.decomposition_iff_matrixAlgorithm
#check MatrixMultiplicationLowerBound.rank_eq
#check MatrixMultiplicationLowerBound.theorem_one_tensorRank

#print axioms MatrixMultiplicationLowerBound.Decomposition.toMatrixAlgorithm
#print axioms MatrixMultiplicationLowerBound.decomposition_iff_matrixAlgorithm
#print axioms MatrixMultiplicationLowerBound.rank_eq
#print axioms MatrixMultiplicationLowerBound.theorem_one_tensorRank
